version: '3'
services:
  reddit-telegram-notifier:
    container_name: reddit-telegram-notifier
    build:
      context: .
      dockerfile: .build/Dockerfile
    restart: always
    volumes:
      - ./search-config.yml:/app/search-config.yml
    env_file:
      - .env
